# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaAbout(object):
    def setupUi(self, VentanaAbout):
        VentanaAbout.setObjectName("VentanaAbout")
        VentanaAbout.resize(800, 639)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VentanaAbout.sizePolicy().hasHeightForWidth())
        VentanaAbout.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(VentanaAbout)
        self.label.setGeometry(QtCore.QRect(-80, 0, 891, 651))
        font = QtGui.QFont()
        font.setFamily("Roman")
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/about.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(VentanaAbout)
        self.label_2.setGeometry(QtCore.QRect(160, 20, 621, 101))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/TEC.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(VentanaAbout)
        self.label_4.setGeometry(QtCore.QRect(300, 180, 501, 211))
        self.label_4.setStyleSheet("background: rgba(0, 69, 124,0.5)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(VentanaAbout)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("\n"
"")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(VentanaAbout)
        self.label_7.setGeometry(QtCore.QRect(630, 220, 151, 141))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("images/daniel.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(VentanaAbout)
        self.label_8.setGeometry(QtCore.QRect(630, 440, 151, 141))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("images/joseph.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(VentanaAbout)
        self.label_9.setGeometry(QtCore.QRect(300, 410, 501, 211))
        self.label_9.setStyleSheet("background: rgba(0, 69, 124,0.5)")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(VentanaAbout)
        self.label_10.setGeometry(QtCore.QRect(620, 210, 171, 161))
        self.label_10.setStyleSheet("background-color: rgba(3, 3, 3,0.5);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(VentanaAbout)
        self.label_11.setGeometry(QtCore.QRect(620, 430, 171, 161))
        self.label_11.setStyleSheet("background-color: rgba(3, 3, 3,0.5);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayoutWidget = QtWidgets.QWidget(VentanaAbout)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 230, 408, 124))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(VentanaAbout)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(310, 450, 408, 124))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(VentanaAbout)
        self.label_16.setGeometry(QtCore.QRect(-220, 180, 501, 441))
        self.label_16.setStyleSheet("background: rgba(0, 69, 124,0.5)")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(VentanaAbout)
        self.label_17.setGeometry(QtCore.QRect(10, 550, 211, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(VentanaAbout)
        self.label_18.setGeometry(QtCore.QRect(10, 490, 211, 36))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(VentanaAbout)
        self.label_19.setGeometry(QtCore.QRect(10, 230, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(VentanaAbout)
        self.label_20.setGeometry(QtCore.QRect(10, 350, 291, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.back = QtWidgets.QPushButton(VentanaAbout)
        self.back.setEnabled(True)
        self.back.setGeometry(QtCore.QRect(620, 140, 166, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setStyleSheet("background:rgba(120, 120, 120, 0.5);\n"
"border: 1px solid;\n"
"")
        self.back.setObjectName("back")
        self.label.raise_()
        self.label_16.raise_()
        self.label_4.raise_()
        self.label_9.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.verticalLayoutWidget.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.back.raise_()

        self.retranslateUi(VentanaAbout)
        QtCore.QMetaObject.connectSlotsByName(VentanaAbout)

    def retranslateUi(self, VentanaAbout):
        _translate = QtCore.QCoreApplication.translate
        VentanaAbout.setWindowTitle(_translate("VentanaAbout", "About"))
        self.label_5.setText(_translate("VentanaAbout", "CEFoot v3.0"))
        self.label_3.setText(_translate("VentanaAbout", "Daniel Castro"))
        self.label_12.setText(_translate("VentanaAbout", "2016165624"))
        self.label_14.setText(_translate("VentanaAbout", "Computer Engineering"))
        self.label_6.setText(_translate("VentanaAbout", "Joseph Vargas"))
        self.label_13.setText(_translate("VentanaAbout", "2016200170"))
        self.label_15.setText(_translate("VentanaAbout", "Computer Engineering"))
        self.label_17.setText(_translate("VentanaAbout", "Costa Rica"))
        self.label_18.setText(_translate("VentanaAbout", "2016"))
        self.label_19.setText(_translate("VentanaAbout", "Taller de\n"
"Programacion"))
        self.label_20.setText(_translate("VentanaAbout", "Professor: Ing.\n"
"Jeff Schmidt\n"
"Peralta"))
        self.back.setText(_translate("VentanaAbout", "Back"))

