# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaCreator(object):
    def setupUi(self, VentanaCreator):
        VentanaCreator.setObjectName("VentanaCreator")
        VentanaCreator.resize(804, 563)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VentanaCreator.sizePolicy().hasHeightForWidth())
        VentanaCreator.setSizePolicy(sizePolicy)
        VentanaCreator.setMinimumSize(QtCore.QSize(804, 563))
        VentanaCreator.setMaximumSize(QtCore.QSize(804, 563))
        self.label = QtWidgets.QLabel(VentanaCreator)
        self.label.setGeometry(QtCore.QRect(0, 0, 831, 571))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/creating.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(VentanaCreator)
        self.label_2.setGeometry(QtCore.QRect(-30, 40, 501, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:rgba(136, 113, 72,0.4);\n"
"border: 1px solid ")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(VentanaCreator)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 110, 451, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.LineName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LineName.setObjectName("LineName")
        self.gridLayout.addWidget(self.LineName, 1, 1, 1, 1)
        self.LineShooterGlobal = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.LineShooterGlobal.setObjectName("LineShooterGlobal")
        self.gridLayout.addWidget(self.LineShooterGlobal, 2, 1, 1, 1)
        self.LineCountry = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.LineCountry.setObjectName("LineCountry")
        self.gridLayout.addWidget(self.LineCountry, 3, 1, 1, 1)
        self.LineAge = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.LineAge.setMinimum(16)
        self.LineAge.setMaximum(40)
        self.LineAge.setObjectName("LineAge")
        self.gridLayout.addWidget(self.LineAge, 4, 1, 1, 1)
        self.LinePeso = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.LinePeso.setMinimum(50)
        self.LinePeso.setMaximum(120)
        self.LinePeso.setObjectName("LinePeso")
        self.gridLayout.addWidget(self.LinePeso, 5, 1, 1, 1)
        self.LineAltura = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.LineAltura.setMinimum(140)
        self.LineAltura.setMaximum(210)
        self.LineAltura.setObjectName("LineAltura")
        self.gridLayout.addWidget(self.LineAltura, 6, 1, 1, 1)
        self.nombreEquipo = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nombreEquipo.setFont(font)
        self.nombreEquipo.setObjectName("nombreEquipo")
        self.gridLayout.addWidget(self.nombreEquipo, 7, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(VentanaCreator)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 510, 574, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background:rgba(136, 113, 72,0.4);\n"
"border: 1px solid ")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.CancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CancelButton.sizePolicy().hasHeightForWidth())
        self.CancelButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.CancelButton.setFont(font)
        self.CancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CancelButton.setStyleSheet("background:rgba(136, 113, 72,0.4);\n"
"border: 1px solid ")
        self.CancelButton.setObjectName("CancelButton")
        self.horizontalLayout.addWidget(self.CancelButton)
        self.ButtonCreate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonCreate.sizePolicy().hasHeightForWidth())
        self.ButtonCreate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ButtonCreate.setFont(font)
        self.ButtonCreate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ButtonCreate.setStyleSheet("background:rgba(136, 113, 72,0.4);\n"
"border: 1px solid ")
        self.ButtonCreate.setObjectName("ButtonCreate")
        self.horizontalLayout.addWidget(self.ButtonCreate)

        self.retranslateUi(VentanaCreator)
        QtCore.QMetaObject.connectSlotsByName(VentanaCreator)

    def retranslateUi(self, VentanaCreator):
        _translate = QtCore.QCoreApplication.translate
        VentanaCreator.setWindowTitle(_translate("VentanaCreator", "Player creation"))
        self.label_2.setText(_translate("VentanaCreator", "Creating a New Player"))
        self.label_4.setText(_translate("VentanaCreator", "Shooter Global:"))
        self.label_5.setText(_translate("VentanaCreator", "Country:"))
        self.label_10.setText(_translate("VentanaCreator", "Height:"))
        self.label_8.setText(_translate("VentanaCreator", "Age:"))
        self.label_9.setText(_translate("VentanaCreator", "Weight:"))
        self.label_11.setText(_translate("VentanaCreator", "Team:"))
        self.label_3.setText(_translate("VentanaCreator", "New Player\'s Name:"))
        self.nombreEquipo.setText(_translate("VentanaCreator", "str(equipo seleccionado)"))
        self.pushButton_3.setText(_translate("VentanaCreator", "Upload a photo"))
        self.CancelButton.setText(_translate("VentanaCreator", "Cancel"))
        self.ButtonCreate.setText(_translate("VentanaCreator", "Create Player"))

