# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'players.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaPlayers(object):
    def setupUi(self, VentanaPlayers):
        VentanaPlayers.setObjectName("VentanaPlayers")
        VentanaPlayers.resize(804, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VentanaPlayers.sizePolicy().hasHeightForWidth())
        VentanaPlayers.setSizePolicy(sizePolicy)
        VentanaPlayers.setMinimumSize(QtCore.QSize(804, 640))
        VentanaPlayers.setMaximumSize(QtCore.QSize(804, 640))
        self.label = QtWidgets.QLabel(VentanaPlayers)
        self.label.setGeometry(QtCore.QRect(-80, -30, 931, 671))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/players.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(VentanaPlayers)
        self.label_3.setGeometry(QtCore.QRect(-20, -40, 441, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/logo ce.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(VentanaPlayers)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 221, 81))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(VentanaPlayers)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 341, 71))
        self.label_5.setStyleSheet("background: rgba(0, 85, 255,0.5)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.ListaJugadores = QtWidgets.QListWidget(VentanaPlayers)
        self.ListaJugadores.setGeometry(QtCore.QRect(10, 180, 341, 321))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ListaJugadores.setFont(font)
        self.ListaJugadores.setStyleSheet("background: rgba(0, 0, 0, 0.65);\n"
"color: rgb(255, 255, 255)")
        self.ListaJugadores.setObjectName("ListaJugadores")
        self.team_label = QtWidgets.QLabel(VentanaPlayers)
        self.team_label.setGeometry(QtCore.QRect(20, 130, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(12)
        self.team_label.setFont(font)
        self.team_label.setStyleSheet("color:rgb(255, 255, 255)")
        self.team_label.setObjectName("team_label")
        self.playerName = QtWidgets.QLabel(VentanaPlayers)
        self.playerName.setGeometry(QtCore.QRect(360, 180, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        self.playerName.setFont(font)
        self.playerName.setStyleSheet("background: rgba(0, 0, 0, 0.7);\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 5px;")
        self.playerName.setObjectName("playerName")
        self.label_7 = QtWidgets.QLabel(VentanaPlayers)
        self.label_7.setGeometry(QtCore.QRect(660, 110, 131, 121))
        self.label_7.setStyleSheet("background:rgba(0,0,0,0.5)")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("images/Madrid.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.dataList = QtWidgets.QListWidget(VentanaPlayers)
        self.dataList.setGeometry(QtCore.QRect(360, 240, 291, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dataList.setFont(font)
        self.dataList.setStyleSheet("background: rgba(0, 0, 0, 0.65);\n"
"color: rgb(255, 255, 255)")
        self.dataList.setObjectName("dataList")
        item = QtWidgets.QListWidgetItem()
        self.dataList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dataList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dataList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dataList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dataList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dataList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dataList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.dataList.addItem(item)
        self.horizontalLayoutWidget = QtWidgets.QWidget(VentanaPlayers)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(440, 30, 341, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.back.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setStyleSheet("background:rgba(120, 120, 120, 0.5);\n"
"border: 1px solid;\n"
"color: rgb(255, 255, 255)")
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back)
        self.continuar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continuar.sizePolicy().hasHeightForWidth())
        self.continuar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.continuar.setFont(font)
        self.continuar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.continuar.setStyleSheet("background:rgba(120, 120, 120, 0.5);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid;")
        self.continuar.setObjectName("continuar")
        self.horizontalLayout.addWidget(self.continuar)
        self.pushButton_3 = QtWidgets.QPushButton(VentanaPlayers)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 110, 291, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("background:rgba(120, 120, 120, 0.5);\n"
"border: 1px solid;\n"
"color: rgb(255, 255, 255)")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(VentanaPlayers)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(660, 240, 131, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sSelect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sSelect.sizePolicy().hasHeightForWidth())
        self.sSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.sSelect.setFont(font)
        self.sSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sSelect.setStyleSheet("background: rgba(0, 0, 0, 0.65);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid;\n"
"")
        self.sSelect.setObjectName("sSelect")
        self.verticalLayout.addWidget(self.sSelect)
        self.gkSelect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gkSelect.sizePolicy().hasHeightForWidth())
        self.gkSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.gkSelect.setFont(font)
        self.gkSelect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gkSelect.setStyleSheet("background: rgba(0, 0, 0, 0.65);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid;")
        self.gkSelect.setObjectName("gkSelect")
        self.verticalLayout.addWidget(self.gkSelect)
        self.horizontalFrame_2 = QtWidgets.QFrame(VentanaPlayers)
        self.horizontalFrame_2.setGeometry(QtCore.QRect(40, 510, 721, 101))
        self.horizontalFrame_2.setStyleSheet("border: 2px solid #000;\n"
"background: #000;\n"
"")
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gk = QtWidgets.QLabel(self.horizontalFrame_2)
        self.gk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gk.setStyleSheet("border: 0;\n"
"border-right: 2px solid #000;\n"
"padding-right: 6px;\n"
"border-radius: 99px;\n"
"overflow: hidden;\n"
"")
        self.gk.setText("")
        self.gk.setPixmap(QtGui.QPixmap("images/myst.jpg"))
        self.gk.setScaledContents(True)
        self.gk.setObjectName("gk")
        self.horizontalLayout_2.addWidget(self.gk)
        self.s1 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.s1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s1.setStyleSheet("border: 0;")
        self.s1.setText("")
        self.s1.setPixmap(QtGui.QPixmap("images/myst.jpg"))
        self.s1.setScaledContents(True)
        self.s1.setObjectName("s1")
        self.horizontalLayout_2.addWidget(self.s1)
        self.s2 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.s2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s2.setStyleSheet("border: 0;\n"
"")
        self.s2.setText("")
        self.s2.setPixmap(QtGui.QPixmap("images/myst.jpg"))
        self.s2.setScaledContents(True)
        self.s2.setObjectName("s2")
        self.horizontalLayout_2.addWidget(self.s2)
        self.s3 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.s3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s3.setStyleSheet("border: 0;")
        self.s3.setText("")
        self.s3.setPixmap(QtGui.QPixmap("images/myst.jpg"))
        self.s3.setScaledContents(True)
        self.s3.setObjectName("s3")
        self.horizontalLayout_2.addWidget(self.s3)
        self.s4 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.s4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s4.setStyleSheet("border: 0;")
        self.s4.setText("")
        self.s4.setPixmap(QtGui.QPixmap("images/myst.jpg"))
        self.s4.setScaledContents(True)
        self.s4.setObjectName("s4")
        self.horizontalLayout_2.addWidget(self.s4)
        self.s5 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.s5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.s5.setStyleSheet("border: 0;")
        self.s5.setText("")
        self.s5.setPixmap(QtGui.QPixmap("images/myst.jpg"))
        self.s5.setScaledContents(True)
        self.s5.setObjectName("s5")
        self.horizontalLayout_2.addWidget(self.s5)
        self.label_14 = QtWidgets.QLabel(VentanaPlayers)
        self.label_14.setGeometry(QtCore.QRect(40, 610, 111, 20))
        self.label_14.setStyleSheet("font-size: 13px;\n"
"font-weight: bold;\n"
"text-transform: uppercase;\n"
"color:#FFF;\n"
"background: #000;\n"
"text-align: center;\n"
"qproperty-alignment: AlignCenter;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(VentanaPlayers)
        self.label_15.setGeometry(QtCore.QRect(150, 610, 611, 20))
        self.label_15.setStyleSheet("font-size: 13px;\n"
"font-weight: bold;\n"
"text-transform: uppercase;\n"
"color:#FFF;\n"
"background: #000;\n"
"text-align: center;\n"
"qproperty-alignment: AlignCenter;")
        self.label_15.setObjectName("label_15")
        self.label.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.ListaJugadores.raise_()
        self.team_label.raise_()
        self.playerName.raise_()
        self.label_7.raise_()
        self.dataList.raise_()
        self.horizontalLayoutWidget.raise_()
        self.pushButton_3.raise_()
        self.verticalLayoutWidget.raise_()
        self.horizontalFrame_2.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.back.raise_()

        self.retranslateUi(VentanaPlayers)
        QtCore.QMetaObject.connectSlotsByName(VentanaPlayers)

    def retranslateUi(self, VentanaPlayers):
        _translate = QtCore.QCoreApplication.translate
        VentanaPlayers.setWindowTitle(_translate("VentanaPlayers", "Form"))
        self.label_2.setText(_translate("VentanaPlayers", "Local"))
        self.team_label.setText(_translate("VentanaPlayers", "%EQUIPO% players:"))
        self.playerName.setText(_translate("VentanaPlayers", "(\"Selected Player\'s Name\")"))
        __sortingEnabled = self.dataList.isSortingEnabled()
        self.dataList.setSortingEnabled(False)
        item = self.dataList.item(0)
        item.setText(_translate("VentanaPlayers", "Shooter Global:"))
        item = self.dataList.item(1)
        item.setText(_translate("VentanaPlayers", "Goalkeeper Global:"))
        item = self.dataList.item(2)
        item.setText(_translate("VentanaPlayers", "Type of Player"))
        item = self.dataList.item(3)
        item.setText(_translate("VentanaPlayers", "Contry:"))
        item = self.dataList.item(4)
        item.setText(_translate("VentanaPlayers", "Age:"))
        item = self.dataList.item(5)
        item.setText(_translate("VentanaPlayers", "Weight:"))
        item = self.dataList.item(6)
        item.setText(_translate("VentanaPlayers", "Height:"))
        item = self.dataList.item(7)
        item.setText(_translate("VentanaPlayers", "Goals:"))
        self.dataList.setSortingEnabled(__sortingEnabled)
        self.back.setText(_translate("VentanaPlayers", "Back"))
        self.continuar.setText(_translate("VentanaPlayers", "Continue"))
        self.pushButton_3.setText(_translate("VentanaPlayers", "Add a new Player"))
        self.sSelect.setText(_translate("VentanaPlayers", "Select\n"
" Shooter"))
        self.gkSelect.setText(_translate("VentanaPlayers", "Select as \n"
" Goalkepper"))
        self.gk.setToolTip(_translate("VentanaPlayers", "<html><head/><body><p>Press to unselect this player.</p></body></html>"))
        self.s1.setToolTip(_translate("VentanaPlayers", "<html><head/><body><p>Press to unselect this player.</p></body></html>"))
        self.s2.setToolTip(_translate("VentanaPlayers", "<html><head/><body><p>Press to unselect this player.</p></body></html>"))
        self.s3.setToolTip(_translate("VentanaPlayers", "<html><head/><body><p>Press to unselect this player.</p></body></html>"))
        self.s4.setToolTip(_translate("VentanaPlayers", "<html><head/><body><p>Press to unselect this player.</p></body></html>"))
        self.s5.setToolTip(_translate("VentanaPlayers", "<html><head/><body><p>Press to unselect this player.</p></body></html>"))
        self.label_14.setText(_translate("VentanaPlayers", "Goalkeeper"))
        self.label_15.setText(_translate("VentanaPlayers", "Shooters"))

