# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'play.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaJuego(object):
    def setupUi(self, VentanaJuego):
        VentanaJuego.setObjectName("VentanaJuego")
        VentanaJuego.resize(802, 638)
        VentanaJuego.setMinimumSize(QtCore.QSize(802, 638))
        VentanaJuego.setMaximumSize(QtCore.QSize(802, 638))
        self.label = QtWidgets.QLabel(VentanaJuego)
        self.label.setGeometry(QtCore.QRect(-80, 0, 961, 641))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/game.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.LocalLabel = QtWidgets.QLabel(VentanaJuego)
        self.LocalLabel.setGeometry(QtCore.QRect(50, 60, 211, 211))
        self.LocalLabel.setMinimumSize(QtCore.QSize(211, 211))
        self.LocalLabel.setMaximumSize(QtCore.QSize(211, 211))
        self.LocalLabel.setText("")
        self.LocalLabel.setPixmap(QtGui.QPixmap("images/barcelona.png"))
        self.LocalLabel.setScaledContents(True)
        self.LocalLabel.setObjectName("LocalLabel")
        self.VisitLabel = QtWidgets.QLabel(VentanaJuego)
        self.VisitLabel.setGeometry(QtCore.QRect(520, 70, 211, 211))
        self.VisitLabel.setMinimumSize(QtCore.QSize(211, 211))
        self.VisitLabel.setMaximumSize(QtCore.QSize(211, 211))
        self.VisitLabel.setText("")
        self.VisitLabel.setPixmap(QtGui.QPixmap("images/barcelona.png"))
        self.VisitLabel.setScaledContents(True)
        self.VisitLabel.setObjectName("VisitLabel")
        self.ShooterPhoto = QtWidgets.QLabel(VentanaJuego)
        self.ShooterPhoto.setGeometry(QtCore.QRect(220, 490, 131, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShooterPhoto.sizePolicy().hasHeightForWidth())
        self.ShooterPhoto.setSizePolicy(sizePolicy)
        self.ShooterPhoto.setMinimumSize(QtCore.QSize(131, 131))
        self.ShooterPhoto.setMaximumSize(QtCore.QSize(131, 131))
        self.ShooterPhoto.setStyleSheet("background:rgba(0,0,0,0.5)")
        self.ShooterPhoto.setText("")
        self.ShooterPhoto.setPixmap(QtGui.QPixmap("images/Madrid.png"))
        self.ShooterPhoto.setScaledContents(True)
        self.ShooterPhoto.setObjectName("ShooterPhoto")
        self.GKPhoto = QtWidgets.QLabel(VentanaJuego)
        self.GKPhoto.setGeometry(QtCore.QRect(630, 490, 131, 131))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GKPhoto.sizePolicy().hasHeightForWidth())
        self.GKPhoto.setSizePolicy(sizePolicy)
        self.GKPhoto.setMinimumSize(QtCore.QSize(131, 131))
        self.GKPhoto.setMaximumSize(QtCore.QSize(131, 131))
        self.GKPhoto.setStyleSheet("background:rgba(0,0,0,0.5)")
        self.GKPhoto.setText("")
        self.GKPhoto.setPixmap(QtGui.QPixmap("images/Madrid.png"))
        self.GKPhoto.setScaledContents(True)
        self.GKPhoto.setObjectName("GKPhoto")
        self.label_5 = QtWidgets.QLabel(VentanaJuego)
        self.label_5.setGeometry(QtCore.QRect(30, 490, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(VentanaJuego)
        self.label_6.setGeometry(QtCore.QRect(360, 490, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_6.setObjectName("label_6")
        self.g4 = QtWidgets.QLabel(VentanaJuego)
        self.g4.setEnabled(False)
        self.g4.setGeometry(QtCore.QRect(480, 390, 81, 81))
        self.g4.setText("")
        self.g4.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g4.setScaledContents(True)
        self.g4.setObjectName("g4")
        self.g6 = QtWidgets.QLabel(VentanaJuego)
        self.g6.setEnabled(False)
        self.g6.setGeometry(QtCore.QRect(550, 390, 81, 81))
        self.g6.setText("")
        self.g6.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g6.setScaledContents(True)
        self.g6.setObjectName("g6")
        self.g2 = QtWidgets.QLabel(VentanaJuego)
        self.g2.setEnabled(False)
        self.g2.setGeometry(QtCore.QRect(410, 390, 81, 81))
        self.g2.setText("")
        self.g2.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g2.setScaledContents(True)
        self.g2.setObjectName("g2")
        self.g8 = QtWidgets.QLabel(VentanaJuego)
        self.g8.setEnabled(False)
        self.g8.setGeometry(QtCore.QRect(620, 390, 81, 81))
        self.g8.setText("")
        self.g8.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g8.setScaledContents(True)
        self.g8.setObjectName("g8")
        self.g10 = QtWidgets.QLabel(VentanaJuego)
        self.g10.setEnabled(False)
        self.g10.setGeometry(QtCore.QRect(690, 390, 81, 81))
        self.g10.setText("")
        self.g10.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g10.setScaledContents(True)
        self.g10.setObjectName("g10")
        self.g7 = QtWidgets.QLabel(VentanaJuego)
        self.g7.setEnabled(False)
        self.g7.setGeometry(QtCore.QRect(240, 390, 81, 81))
        self.g7.setText("")
        self.g7.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g7.setScaledContents(True)
        self.g7.setObjectName("g7")
        self.g5 = QtWidgets.QLabel(VentanaJuego)
        self.g5.setEnabled(False)
        self.g5.setGeometry(QtCore.QRect(170, 390, 81, 81))
        self.g5.setText("")
        self.g5.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g5.setScaledContents(True)
        self.g5.setObjectName("g5")
        self.g9 = QtWidgets.QLabel(VentanaJuego)
        self.g9.setEnabled(False)
        self.g9.setGeometry(QtCore.QRect(310, 390, 81, 81))
        self.g9.setText("")
        self.g9.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g9.setScaledContents(True)
        self.g9.setObjectName("g9")
        self.g1 = QtWidgets.QLabel(VentanaJuego)
        self.g1.setEnabled(False)
        self.g1.setGeometry(QtCore.QRect(30, 390, 81, 81))
        self.g1.setText("")
        self.g1.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g1.setScaledContents(True)
        self.g1.setObjectName("g1")
        self.g3 = QtWidgets.QLabel(VentanaJuego)
        self.g3.setEnabled(False)
        self.g3.setGeometry(QtCore.QRect(100, 390, 81, 81))
        self.g3.setText("")
        self.g3.setPixmap(QtGui.QPixmap("images/104493-3d-glossy-green-orb-icon-sports-hobbies-ball-soccer.png"))
        self.g3.setScaledContents(True)
        self.g3.setObjectName("g3")
        self.label_7 = QtWidgets.QLabel(VentanaJuego)
        self.label_7.setGeometry(QtCore.QRect(90, 300, 331, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(49)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_7.setObjectName("label_7")
        self.LocalLabel_2 = QtWidgets.QLabel(VentanaJuego)
        self.LocalLabel_2.setGeometry(QtCore.QRect(330, 140, 141, 131))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.LocalLabel_2.setFont(font)
        self.LocalLabel_2.setObjectName("LocalLabel_2")
        self.label_9 = QtWidgets.QLabel(VentanaJuego)
        self.label_9.setGeometry(QtCore.QRect(100, 300, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(48)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.label_30 = QtWidgets.QLabel(VentanaJuego)
        self.label_30.setGeometry(QtCore.QRect(510, 300, 261, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(48)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("")
        self.label_30.setObjectName("label_30")
        self.label_8 = QtWidgets.QLabel(VentanaJuego)
        self.label_8.setGeometry(QtCore.QRect(500, 300, 331, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(49)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(VentanaJuego)
        self.pushButton.setGeometry(QtCore.QRect(690, 0, 121, 51))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background:rgba(10, 10, 10, 0.5);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(VentanaJuego)
        self.label_2.setGeometry(QtCore.QRect(0, 490, 801, 131))
        self.label_2.setStyleSheet("background:rgba(0,0,0,0.5)")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.LocalLabel.raise_()
        self.VisitLabel.raise_()
        self.g4.raise_()
        self.g6.raise_()
        self.g2.raise_()
        self.g8.raise_()
        self.g10.raise_()
        self.g7.raise_()
        self.g5.raise_()
        self.g9.raise_()
        self.g1.raise_()
        self.g3.raise_()
        self.label_7.raise_()
        self.LocalLabel_2.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label_30.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.ShooterPhoto.raise_()
        self.GKPhoto.raise_()

        self.retranslateUi(VentanaJuego)
        QtCore.QMetaObject.connectSlotsByName(VentanaJuego)

    def retranslateUi(self, VentanaJuego):
        _translate = QtCore.QCoreApplication.translate
        VentanaJuego.setWindowTitle(_translate("VentanaJuego", "Play"))
        self.label_5.setText(_translate("VentanaJuego", "Shooter:"))
        self.label_6.setText(_translate("VentanaJuego", "Goalkeeper:"))
        self.label_7.setText(_translate("VentanaJuego", "LOCAL"))
        self.LocalLabel_2.setText(_translate("VentanaJuego", "VS"))
        self.label_9.setText(_translate("VentanaJuego", "LOCAL"))
        self.label_30.setText(_translate("VentanaJuego", "VISIT"))
        self.label_8.setText(_translate("VentanaJuego", "VISIT"))
        self.pushButton.setText(_translate("VentanaJuego", "End this game"))

