# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teams.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VentanaSelector(object):
    def setupUi(self, VentanaSelector):
        VentanaSelector.setObjectName("VentanaSelector")
        VentanaSelector.resize(799, 561)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VentanaSelector.sizePolicy().hasHeightForWidth())
        VentanaSelector.setSizePolicy(sizePolicy)
        VentanaSelector.setStyleSheet("QPushButton {\n"
"background: rgba(0,0,0,0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 3px dashed #222;\n"
"background: rgba(5,5,5,0.2);\n"
"}\n"
"\n"
"\n"
"QPushButton:checked {\n"
"border:3px solid #222;\n"
"background: rgba(5,5,5,0.5);\n"
"}")
        self.label = QtWidgets.QLabel(VentanaSelector)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(-10, 0, 811, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMouseTracking(False)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setAccessibleName("")
        self.label.setAutoFillBackground(False)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(1)
        self.label.setMidLineWidth(0)
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setPixmap(QtGui.QPixmap("images/choose.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(VentanaSelector)
        self.label_3.setGeometry(QtCore.QRect(-20, -30, 441, 151))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/logo ce.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(VentanaSelector)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 171, 81))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(VentanaSelector)
        self.label_4.setGeometry(QtCore.QRect(630, 90, 201, 81))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(36)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(VentanaSelector)
        self.label_5.setGeometry(QtCore.QRect(0, 100, 351, 61))
        self.label_5.setStyleSheet("background: rgba(0, 85, 255,0.5)")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(VentanaSelector)
        self.label_6.setGeometry(QtCore.QRect(450, 100, 351, 61))
        self.label_6.setStyleSheet("background: rgba(0, 85, 255,0.5)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayoutWidget = QtWidgets.QWidget(VentanaSelector)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 160, 351, 403))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.L1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.L1.setEnabled(True)
        self.L1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L1.setStyleSheet("")
        self.L1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/barcelona.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("images/barcelona.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.L1.setIcon(icon)
        self.L1.setIconSize(QtCore.QSize(115, 115))
        self.L1.setCheckable(True)
        self.L1.setChecked(False)
        self.L1.setObjectName("L1")
        self.gridLayout.addWidget(self.L1, 0, 0, 1, 1)
        self.L3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.L3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/Bayern.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.L3.setIcon(icon1)
        self.L3.setIconSize(QtCore.QSize(120, 120))
        self.L3.setCheckable(True)
        self.L3.setObjectName("L3")
        self.gridLayout.addWidget(self.L3, 1, 0, 1, 1)
        self.L2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.L2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/Madrid.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.L2.setIcon(icon2)
        self.L2.setIconSize(QtCore.QSize(120, 120))
        self.L2.setCheckable(True)
        self.L2.setObjectName("L2")
        self.gridLayout.addWidget(self.L2, 0, 1, 1, 1)
        self.L4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.L4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/psg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.L4.setIcon(icon3)
        self.L4.setIconSize(QtCore.QSize(120, 120))
        self.L4.setCheckable(True)
        self.L4.setObjectName("L4")
        self.gridLayout.addWidget(self.L4, 1, 1, 1, 1)
        self.L5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.L5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/arsenal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.L5.setIcon(icon4)
        self.L5.setIconSize(QtCore.QSize(120, 120))
        self.L5.setCheckable(True)
        self.L5.setObjectName("L5")
        self.gridLayout.addWidget(self.L5, 2, 0, 1, 1)
        self.L6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.L6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/juventus-hd-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.L6.setIcon(icon5)
        self.L6.setIconSize(QtCore.QSize(120, 120))
        self.L6.setCheckable(True)
        self.L6.setObjectName("L6")
        self.gridLayout.addWidget(self.L6, 2, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(VentanaSelector)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(450, 160, 351, 403))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.L1_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.L1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L1_2.setStyleSheet("")
        self.L1_2.setText("")
        self.L1_2.setIcon(icon)
        self.L1_2.setIconSize(QtCore.QSize(115, 115))
        self.L1_2.setCheckable(True)
        self.L1_2.setChecked(False)
        self.L1_2.setObjectName("L1_2")
        self.gridLayout_2.addWidget(self.L1_2, 0, 0, 1, 1)
        self.L3_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.L3_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L3_2.setText("")
        self.L3_2.setIcon(icon1)
        self.L3_2.setIconSize(QtCore.QSize(120, 120))
        self.L3_2.setCheckable(True)
        self.L3_2.setObjectName("L3_2")
        self.gridLayout_2.addWidget(self.L3_2, 1, 0, 1, 1)
        self.L2_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.L2_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L2_2.setText("")
        self.L2_2.setIcon(icon2)
        self.L2_2.setIconSize(QtCore.QSize(120, 120))
        self.L2_2.setCheckable(True)
        self.L2_2.setObjectName("L2_2")
        self.gridLayout_2.addWidget(self.L2_2, 0, 1, 1, 1)
        self.L4_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.L4_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L4_2.setText("")
        self.L4_2.setIcon(icon3)
        self.L4_2.setIconSize(QtCore.QSize(120, 120))
        self.L4_2.setCheckable(True)
        self.L4_2.setObjectName("L4_2")
        self.gridLayout_2.addWidget(self.L4_2, 1, 1, 1, 1)
        self.L5_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.L5_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L5_2.setText("")
        self.L5_2.setIcon(icon4)
        self.L5_2.setIconSize(QtCore.QSize(120, 120))
        self.L5_2.setCheckable(True)
        self.L5_2.setObjectName("L5_2")
        self.gridLayout_2.addWidget(self.L5_2, 2, 0, 1, 1)
        self.L6_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.L6_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.L6_2.setText("")
        self.L6_2.setIcon(icon5)
        self.L6_2.setIconSize(QtCore.QSize(120, 120))
        self.L6_2.setCheckable(True)
        self.L6_2.setObjectName("L6_2")
        self.gridLayout_2.addWidget(self.L6_2, 2, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(VentanaSelector)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(450, 30, 341, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.back.setFont(font)
        self.back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back.setStyleSheet("background:rgba(120, 120, 120, 0.5);\n"
"border: 1px solid;\n"
"color: rgb(255, 255, 255)")
        self.back.setObjectName("back")
        self.horizontalLayout.addWidget(self.back)
        self.continuar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.continuar.sizePolicy().hasHeightForWidth())
        self.continuar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.continuar.setFont(font)
        self.continuar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.continuar.setStyleSheet("background:rgba(10, 10, 10, 0.5);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid;")
        self.continuar.setObjectName("continuar")
        self.horizontalLayout.addWidget(self.continuar)
        self.label.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.horizontalLayoutWidget.raise_()

        self.retranslateUi(VentanaSelector)
        QtCore.QMetaObject.connectSlotsByName(VentanaSelector)
        VentanaSelector.setTabOrder(self.L1, self.L2)
        VentanaSelector.setTabOrder(self.L2, self.L3)
        VentanaSelector.setTabOrder(self.L3, self.L4)
        VentanaSelector.setTabOrder(self.L4, self.L5)
        VentanaSelector.setTabOrder(self.L5, self.L6)
        VentanaSelector.setTabOrder(self.L6, self.L1_2)
        VentanaSelector.setTabOrder(self.L1_2, self.L2_2)
        VentanaSelector.setTabOrder(self.L2_2, self.L3_2)
        VentanaSelector.setTabOrder(self.L3_2, self.L4_2)
        VentanaSelector.setTabOrder(self.L4_2, self.L5_2)
        VentanaSelector.setTabOrder(self.L5_2, self.L6_2)
        VentanaSelector.setTabOrder(self.L6_2, self.back)
        VentanaSelector.setTabOrder(self.back, self.continuar)

    def retranslateUi(self, VentanaSelector):
        _translate = QtCore.QCoreApplication.translate
        VentanaSelector.setWindowTitle(_translate("VentanaSelector", "Teams Selector"))
        self.label_2.setText(_translate("VentanaSelector", "Local"))
        self.label_4.setText(_translate("VentanaSelector", "Visit"))
        self.back.setText(_translate("VentanaSelector", "Back"))
        self.continuar.setText(_translate("VentanaSelector", "Continue"))

